CREATE DATABASE preguntas_dinamicas;
USE preguntas_dinamicas;

CREATE TABLE CATEGORIAS(
    ID_CATEGORIA INT NOT NULL AUTO_INCREMENT,
    CATEGORIA VARCHAR(50) NOT NULL,    
    CONSTRAINT PK_CATEGORIA PRIMARY KEY(ID_CATEGORIA)
);

CREATE TABLE PREGUNTAS(
    ID_PREGUNTA INT NOT NULL AUTO_INCREMENT,
    PREGUNTA VARCHAR(100) NOT NULL,
    ID_CATEGORIA INT NOT NULL,
    CONSTRAINT PK_PREGUNTA PRIMARY KEY(ID_PREGUNTA),
    CONSTRAINT FK_PREGUNTA_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);

CREATE TABLE RESPUESTAS(
    ID_RESPUESTA INT NOT NULL AUTO_INCREMENT,
    RESPUESTA VARCHAR(100) NOT NULL,
    ID_PREGUNTA INT NOT NULL,
    CONSTRAINT PK_RESPUESTA PRIMARY KEY(ID_RESPUESTA),
    CONSTRAINT FK_RESPUESTA_PREGUNTA FOREIGN KEY(ID_PREGUNTA) REFERENCES PREGUNTAS(ID_PREGUNTA)
);