use db_sp;
SELECT * FROM USUARIOS WHERE ID_USUARIO = "usuario1" AND PASSWORD = "password1";

SELECT C.ID_CONVOCATORIA, PU.ID_PUESTO, US.ID_USUARIO AS CREADOR, PU.TITULO AS PUESTO, C.FECHA_INICIO, C.FECHA_FIN, C.OBSERVACIONES
FROM CONVOCATORIAS AS C
INNER JOIN PUESTOS AS PU ON PU.ID_PUESTO = C.ID_PUESTO
INNER JOIN USUARIOS AS US ON US.ID_USUARIO = C.ID_USUARIO

SELECT C.ID_CONVOCATORIA, PU.ID_PUESTO, US.ID_USUARIO AS CREADOR, PU.TITULO AS PUESTO, C.FECHA_INICIO, C.FECHA_FIN, C.OBSERVACIONES 
FROM CONVOCATORIAS AS C
INNER JOIN PUESTOS AS PU ON PU.ID_PUESTO = C.ID_PUESTO
INNER JOIN USUARIOS AS US ON US.ID_USUARIO = C.ID_USUARIO
WHERE C.ID_ESTADO = 1
ORDER BY C.ID_CONVOCATORIA


SELECT POS.*, GEN.GENERO
FROM postulantes AS POS
INNER JOIN generos AS GEN 
ON POS.ID_GENERO = GEN.ID_GENERO
WHERE POS.ID_ESTADO = 1
ORDER BY POS.ID_POSTULANTE;

SELECT POST.*, PUES.ID_PUESTO, PUES.TITULO AS PUESTO, CONCAT(POSTU.NOMBRES,' ',POSTU.APELLIDOS) AS POSTULANTE
FROM postulaciones AS POST
INNER JOIN convocatorias AS C ON C.ID_CONVOCATORIA = POST.ID_CONVOCATORIA
INNER JOIN puestos AS PUES ON PUES.ID_PUESTO = C.ID_PUESTO
INNER JOIN postulantes AS POSTU ON POSTU.ID_POSTULANTE = POST.ID_POSTULANTE
WHERE C.ID_PUESTO = 1 AND POST.ID_ESTADO = 1
ORDER BY POST.ID_POSTULACION


SELECT ID_CONVOCATORIA, CONCAT(FECHA_INICIO,' | ',FECHA_FIN) AS CONVOCATORIA
FROM convocatorias
WHERE ID_PUESTO = 1 AND ID_ESTADO = 1

SELECT ID_POSTULANTE, CONCAT(NOMBRES,' ',APELLIDOS) AS POSTULANTE
FROM postulantes
ORDER BY POSTULANTE

SELECT *
FROM postulaciones
WHERE ID_CONVOCATORIA = 25 AND ID_POSTULANTE = 6 AND ID_ESTADO = 1


UPDATE POSTULANTES SET ID_ESTADO= 2 WHERE ID_POSTULANTE = 6

SELECT PP.ID_POSTULANTE, PP.APELLIDOS, PP.NOMBRES, C.ID_CONVOCATORIA, DATE_FORMAT(C.FECHA_INICIO, '%d/%m/%Y') AS 'INICIO CONVOCATORIA', DATE_FORMAT(C.FECHA_FIN, '%d/%m/%Y') AS 'FIN CONVOCATORIA', P.ID_POSTULACION, P.FECHA_POSTULACION, EE.ID_ESTADO_ENTREVISTA, EE.ESTADO_ENTREVISTA, PU.ID_PUESTO
FROM postulaciones AS P
INNER JOIN postulantes AS PP ON PP.ID_POSTULANTE = P.ID_POSTULANTE
INNER JOIN convocatorias AS C ON C.ID_CONVOCATORIA = P.ID_CONVOCATORIA
INNER JOIN puestos AS PU ON PU.ID_PUESTO = C.ID_PUESTO
INNER JOIN estados_entrevista AS EE ON EE.ID_ESTADO_ENTREVISTA = P.ID_ESTADO_ENTREVISTA
WHERE PU.ID_PUESTO = 1 AND P.ID_ESTADO = 1 AND C.ID_ESTADO = 1
ORDER BY PP.APELLIDOS

USE db_sp;
SELECT * FROM PREGUNTAS WHERE ID_PUESTO = 3 AND ID_ESTADO=1

SELECT * FROM respuestas WHERE ID_PREGUNTA = 12 AND ID_ESTADO=1

SELECT PU.ID_PUESTO, PU.TITULO, PR.ID_PREGUNTA, PR.PREGUNTA, RE.ID_RESPUESTA, RE.RESPUESTA FROM PUESTOS AS PU
INNER JOIN PREGUNTAS AS PR ON PR.ID_PUESTO = PU.ID_PUESTO
INNER JOIN RESPUESTAS AS RE ON RE.ID_PREGUNTA = PR.ID_PREGUNTA
WHERE PR.ID_PUESTO = 3 

TRUNCATE TABLE resultados

UPDATE POSTULACIONES
SET ID_ESTADO_ENTREVISTA = 1

SELECT POST.*, PUES.ID_PUESTO, PUES.TITULO AS PUESTO, CONCAT(POSTU.NOMBRES,' ',POSTU.APELLIDOS) AS POSTULANTE
FROM postulaciones AS POST 
INNER JOIN convocatorias AS C ON C.ID_CONVOCATORIA = POST.ID_CONVOCATORIA 
INNER JOIN puestos AS PUES ON PUES.ID_PUESTO = C.ID_PUESTO 
INNER JOIN postulantes AS POSTU ON POSTU.ID_POSTULANTE = POST.ID_POSTULANTE 
WHERE C.ID_PUESTO = 1 AND POST.ID_ESTADO = 1

SELECT PU.ID_PUESTO, PRE.ID_PREGUNTA, PRE.PREGUNTA
FROM puestos AS PU
INNER JOIN preguntas AS PRE ON PRE.ID_PUESTO = PU.ID_PUESTO
WHERE PU.ID_PUESTO = 4 AND PU.ID_ESTADO = 1 AND PRE.ID_ESTADO = 1
ORDER BY ID_PREGUNTA

SELECT PU.ID_PUESTO, PU.TITULO, PR.ID_PREGUNTA, PR.PREGUNTA, RE.ID_RESPUESTA, RE.RESPUESTA, RE.ID_ESTADO, RE.`VALOR`
FROM PUESTOS AS PU
INNER JOIN PREGUNTAS AS PR ON PR.ID_PUESTO = PU.ID_PUESTO
INNER JOIN RESPUESTAS AS RE ON RE.ID_PREGUNTA = PR.ID_PREGUNTA
WHERE PR.ID_PUESTO = 3 

-- CONTAR TOTAL DE RESPUESTAS ACTIVAS POR ENTREVISTA
SELECT COUNT(RE.ID_RESPUESTA) AS TOTAL_ENTREVISTA
FROM puestos AS PU
INNER JOIN preguntas AS PR ON PR.ID_PUESTO = PU.ID_PUESTO
INNER JOIN respuestas AS RE ON RE.ID_PREGUNTA = PR.ID_PREGUNTA
WHERE RE.ID_ESTADO = 1 AND PR.ID_ESTADO = 1 AND PU.ID_ESTADO = 1 AND PU.ID_PUESTO = 3

SELECT SUM(RESS.VALOR) AS TOTAL_OBTENIDO
FROM postulaciones AS POS 
INNER JOIN resultados AS RES ON RES.ID_POSTULACION = POS.ID_POSTULACION
INNER JOIN respuestas AS RESS ON RESS.ID_RESPUESTA = RES.ID_RESPUESTA
WHERE POS.ID_ESTADO= 1 AND RESS.ID_ESTADO = 1 AND POS.ID_POSTULACION = 2

-- CONSULTA DE RESULTADOS FINALES
SELECT CONCAT(PP.NOMBRES,' ', PP.APELLIDOS) AS POSTULANTE, ROUND((P.VALOR_ENTREVISTA_OBTENIDO / P.VALOR_ENTREVISTA)*100) AS RESULTADO
FROM convocatorias AS C
INNER JOIN postulaciones AS P ON P.ID_CONVOCATORIA = C.ID_CONVOCATORIA
INNER JOIN postulantes AS PP ON PP.ID_POSTULANTE = P.ID_POSTULANTE
WHERE C.ID_CONVOCATORIA = 2 AND C.ID_ESTADO = 1 AND P.ID_ESTADO = 1 AND PP.ID_ESTADO = 1

SELECT C.ID_CONVOCATORIA, DATE_FORMAT(C.FECHA_INICIO, '%d/%m/%Y'), DATE_FORMAT(C.FECHA_FIN, '%d/%m/%Y'), OBSERVACIONES, P.ID_PUESTO, TITULO, DESCRIPCION, PERFIL
FROM convocatorias AS C
INNER JOIN puestos AS P ON P.ID_PUESTO = C.ID_PUESTO
WHERE C.ID_CONVOCATORIA = 1

SELECT POST.*, PUES.ID_PUESTO, PUES.TITULO AS PUESTO, CONCAT(POSTU.NOMBRES,' ',POSTU.APELLIDOS) AS POSTULANTE
FROM postulaciones AS POST 
INNER JOIN convocatorias AS C ON C.ID_CONVOCATORIA = POST.ID_CONVOCATORIA 
INNER JOIN puestos AS PUES ON PUES.ID_PUESTO = C.ID_PUESTO 
INNER JOIN postulantes AS POSTU ON POSTU.ID_POSTULANTE = POST.ID_POSTULANTE 
WHERE C.ID_CONVOCATORIA =  5  AND POST.ID_ESTADO = 1 

SELECT PU.ID_PUESTO, PRE.ID_PREGUNTA, PRE.PREGUNTA FROM puestos AS PU 
INNER JOIN preguntas AS PRE ON PRE.ID_PUESTO = PU.ID_PUESTO  
WHERE PU.ID_PUESTO = 6 AND PU.ID_ESTADO = 1 AND PRE.ID_ESTADO = 1  
ORDER BY ID_PREGUNTA;

SELECT P.ID_POSTULACION, CONCAT(PP.NOMBRES,' ', PP.APELLIDOS) AS POSTULANTE, 
ROUND((P.VALOR_ENTREVISTA_OBTENIDO / P.VALOR_ENTREVISTA)*100) AS RESULTADO  
FROM convocatorias AS C  
INNER JOIN postulaciones AS P ON P.ID_CONVOCATORIA = C.ID_CONVOCATORIA  
INNER JOIN postulantes AS PP ON PP.ID_POSTULANTE = P.ID_POSTULANTE  
WHERE C.ID_CONVOCATORIA = 6 AND C.ID_ESTADO = 1 AND P.ID_ESTADO = 1 AND PP.ID_ESTADO = 1

SELECT C.ID_CONVOCATORIA, C.FECHA_INICIO, FECHA_FIN, P.TITULO FROM CONVOCATORIAS AS C INNER JOIN puestos AS P ON P.ID_PUESTO = C.ID_PUESTO WHERE ID_CONVOCATORIA =2